# Generated by Django 6.0.6 on 2026-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_name',
            new_name='topic_name',
        ),
    ]
