# Generated by Django 6.0.6 on 2026-07-09 14:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0003_accessrecord_count_alter_accessrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('number_of_employees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=264, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zing_it.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=264, unique=True)),
                ('employee_name', models.ManyToManyField(to='zing_it.employee')),
            ],
        ),
    ]
